### ISSUE TITLE
CPT Conflict

### ISSUE THREAD

**Issue by leepeterson** [stuttter/wp-user-activity#12]
Our dev team created a CPT named "activity". Once this plugin was activated, the posts for the activity CPT were replaced with blank information and this plugin created 1 new post at the top of list, a post which now cannot be deleted when this plugin is active or deactivated.

Here's a fun video which explains more: http://snap.rawlemurdy.host/k2fx

We're going to namespace our CPTs (which should have been done to begin with) but thought this issue should be brought to your attention.

**Comment by JJJ** [comment]
Hey @leepeterson, thanks for the heads up.

I probably should have namespaced it. I had a feeling `activity` would be a relatively popular post type, but didn't expect for multiple types of activity based plugins to be active at one time.
