### ISSUE TITLE
why no uninstall.php?

### ISSUE THREAD

**Issue by pbiron** [stuttter/wp-user-activity#13]
I just ran into a conflict between this plugin and the [Custom Permalinks](https://wordpress.org/plugins/custom-permalinks/) plugin.  The problem is in that other plugin, my bug report to the author of that plugin is [here](https://wordpress.org/support/topic/doesnt-play-well-with-wp-user-activity-plugin/).

I thought I could temporarily resolve the conflict by deleting this plugin (in the hopes that doing so would delete all of the posts with post_type == 'activity' which are causing the conflict in the presence of that other plugin's bug)...but alas, you don't have an `uninstall.php`, so I had to manually remove the data from the db.

**Comment by szepeviktor** [comment]
You could use WP-CLI to clean up activities:

```bash
wp post list --post_type=activity --format=count
wp post delete $(wp post list --post_type=activity --format=ids)
```

**Comment by JJJ** [comment]
The `uninstall.php` approach is dangerous for plugins like WP User Activity, because it's a single click in the plugin row that would obliterate all plugin data without any notice.

I think it's nice for cleaning up stray options & settings, but not potentially thousands of rows.

**Comment by szepeviktor** [comment]
OK.
