### ISSUE TITLE
(no title) phantom post creation

### ISSUE THREAD

**Issue by Log1x** [stuttter/wp-user-activity#18]
Hi.

I really like the concept of wp-user-activity and you've implemented it wonderfully.

Right now, it seems to have a very annoying bug when modifying or editing a post and saving changes, wp-user-activity will create a random phantom post with the page name: (no title).

![Screenshot](https://log1x.com/screenshots/2017-08-28_20-42-14_ZQL23.png)

I'd love to get this sorted out!

Thanks

**Comment by Log1x** [comment]
If you can point me in the right direction on where this issue would be arising, I can attempt a PR.

**Comment by JJJ** [comment]
Sorry for the delay here. I haven't been able to duplicate this, but it's likely related to revisions or some other plugin that's doing something I haven't conditionally trapped.

What plugins are you running in conjunction with this one?

**Comment by Log1x** [comment]
The main plugin I can think that'd have an effect would be ACF.

**Comment by JJJ** [comment]
👍
