### ISSUE TITLE
Limit number of activities

### ISSUE THREAD

**Issue by szepeviktor** [stuttter/wp-user-activity#20]
It would be nice to daily check the number of activities and purge old ones.
Let's say keep the last `apply_filters( 10,000 )`

**Comment by JJJ** [comment]
Created a project for this:

https://github.com/stuttter/wp-user-activity/projects/1?

**Comment by leepeterson** [comment]
Just wanted to comment that either a filter to manage database entries as @szepeviktor requested, or the option to move all this data somewhere else entirely — be it a database, static files, postgres, mongodb... whatever — would be wonderful.

In the process of cleaning out a database which ran this plugin for ~6 months last year, came across this:
`SELECT * FROM wp_postmeta WHERE (meta_key LIKE '%wp_user_activity_%' OR meta_value LIKE '%wp_user_activity_%')` which resulted in `231,209 rows`

Not that this has caused any _problems_ per se, but... dang.

**Comment by JJJ** [comment]
Would like to setup a WordPress Cron job to clean up excess activity items, capped at 10k to start.

**Comment by seancojr** [comment]
> Would like to setup a WordPress Cron job to clean up excess activity items, capped at 10k to start.

I have this plugin under consideration for a client's site. Is this feature still on the development roadmap?

**Comment by szepeviktor** [comment]
> I have this plugin under consideration for a client's site.

You can achieve this using WP-CLI in a Linux cron job.

**Comment by JJJ** [comment]
> I have this plugin under consideration for a client's site. Is this feature still on the development roadmap?

Yes 👍

**Comment by JJJ** [comment]
Fixed as part of #25, limiting to last 14 days.
