### ISSUE TITLE
no details to recorded activity

### ISSUE THREAD

**Issue by modemlooper** [stuttter/wp-user-activity#6]
The actions are added but its all blank for each one. 

![empty](https://cloud.githubusercontent.com/assets/867885/11325830/1069941c-910d-11e5-8dea-b16ffcc02d3e.png)

**Comment by modemlooper** [comment]
![empty](https://cloud.githubusercontent.com/assets/867885/11325834/236935a4-910d-11e5-932f-cb6a16965382.png)

**Comment by modemlooper** [comment]
brand new WP 4.3.1 install with nothing else active.

**Comment by JJJ** [comment]
Still happening with 4.4?

**Comment by JJJ** [comment]
This seems fixed. Go ahead and reopen if it's not.
